export const UPDATE_VIEW_SETTINGS = 'UPDATE_VIEW_SETTINGS';
export const G_CLICKED = 'G_CLICKED';
export const ADD_INPUT_VALUE_CHANGED = 'ADD_INPUT_VALUE_CHANGED';
export const ADD_INPUT_TAG_CHANGED = 'ADD_INPUT_TAG_CHANGED';
export const ADD_PROJECT_FORM = 'ADD_PROJECT_FORM';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const UPDATE_PROJECT_ITEMS = 'UPDATE_PROJECT_ITEM';
export const UPDATE_PROJECT_CONTAINER = 'UPDATE_PROJECT_CONTAINER';