export const UPDATE_VIEW_SETTINGS = 'UPDATE_VIEW_SETTINGS';
export const G_CLICKED = 'G_CLICKED';
export const ADD_INPUT_VALUE_CHANGED = 'ADD_INPUT_VALUE_CHANGED';
export const ADD_INPUT_TAG_CHANGED = 'ADD_INPUT_TAG_CHANGED';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';