-- dbo.user
CREATE TABLE [dbo].[users](
	[user_id] [varchar](100) NOT NULL,
	[email] [varchar](500) NOT NULL,
	[passhash] [varchar](500) NOT NULL,
	[recovertoken] [varchar](500) NULL,
PRIMARY KEY CLUSTERED 
(
	[user_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


-- STOP HERE AND ENSURE TCP/IP CONNECTIONS ARE ENABLED AND SQL SERVER BROWSER SERVICE IS RUNNING