export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const UPDATE_PROJECT_ITEMS = 'UPDATE_PROJECT_ITEM';
export const UPDATE_PROJECT_CONTAINER = 'UPDATE_PROJECT_CONTAINER';
export const INIT_PROJECT = 'INIT_PROJECT';
export const UPDATE_PROJECT_CONFIG = 'UPDATE_PROJECT_CONFIG';